### ISSUE TITLE
High memory allocation

### ISSUE THREAD

**Issue by ZepsiZola** [ryderbelserion/Pl3xMapExtras#21]
### Spark link

https://spark.lucko.me/2GLmeSFYmU

### Plugin Version

1.2.0

### Server Version

1.21.3

### Server Platform

Paper

### Describe the bug

There's an unusually high memory allocation on the Pl3xMap-Markers thread. By high I mean 1.3GB per second. Also weird because I set it so that the claims layer should only refresh once per hour.

![Image](https://github.com/user-attachments/assets/0996a24d-c98b-46c6-8e66-f0849b4df960)

### Steps to reproduce

I have GriefPrevention installed.
I have Pl3xMap and Pl3xMapExtras installed.
I am on Leaf 1.21.5.

### Additional context

This is my `Pl3xMapExtras/claims/griefprevention.yml` file
```YAML
settings:
  layer:
    # Label for map layer
    label: Claims
    # Show controls for map layer
    show-controls: true
    # Whether map layer is hidden by default
    default-hidden: true
    # Update interval for map layer
    update-interval: 3600
    # Priority for map layer
    priority: 10
    # zIndex for map layer
    z-index: 10
  claim:
    basic:
      stroke:
        # Stroke color (#AARRGGBB)
        color: '#AA00FF00'
        # Stroke weight
        weight: 2
      fill:
        # Fill color (#AARRGGBB)
        color: '#3300FF00'
      # Popup for basic claims
      popup: |-
        <span style="font-weight:bold;">Land-Claim Info</span><br/>
        Area: <span style="font-weight:bold;"><area></span><br/>
        Height: <span style="font-weight:bold;"><height></span><br/>
        Width: <span style="font-weight:bold;"><width></span><br/>
    admin:
      stroke:
        # Stroke color (#AARRGGBB)
        color: '#AA00FF00'
        # Stroke weight
        weight: 2
      fill:
        # Fill color (#AARRGGBB)
        color: '#3300FF00'
      # Popup for admin claims
      popup: |-
        <span style="font-weight:bold;">Land-Claim Info</span><br/>
        Area: <span style="font-weight:bold;"><area></span><br/>
        Height: <span style="font-weight:bold;"><height></span><br/>
        Width: <span style="font-weight:bold;"><width></span><br/>
    popup:
      # Popup text for trusts if present
      trust: 'Trust: <span style="font-weight:bold;"><builders></span><br/>'
      # Popup text for container trusts if present
      container: 'Container: <span style="font-weight:bold;"><containers></span><br/>'
      # Popup text for trusts if present
      access: 'Access: <span style="font-weight:bold;"><accessors></span><br/>'
      # Popup text for trusts if present
      permission: 'Permission: <span style="font-weight:bold;"><managers></span><br/>'
```

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [x] My version of Minecraft is supported.
